defaults:

  - scope:
        path: ""
        type: posts

    values:
        layout: "recipe"

        image: ""
        tags: []

        source: "[site name or book name]"
        sourceURL: ""
        sourceAuthor: "by [Author], p[n]"

        yield: "Makes []"

        authorNote: ""
        personalNote: ""

        ingredients: []

        totalTime: ""

        prepTime: ""
        handsoffTime: ""
        cookTime: ""
        chillTime: ""
        assemblyTime: ""
        reheatTime: ""

  - scope:
        path: ""
        type: posts

    values:
        layout: "default"

        image: ""
        tags: []


