defaults:
  - scope:
        path: ""
        type: posts
    values:
        image: ""
        tags: []
        source: ""
        yield: "default yield"

        authorNote: ""
        personalNote: ""

        ingredients: []

        totalTime: ""
        prepTime: ""
        handsoffTime: ""
        cookTime: ""
        assemblyTime: ""
        reheatTime: ""
