defaults:
  - scope:
        path: ""
        type: posts
    values:
        thumbnail: ""
        tags: []
        authorNote: ""
        personalNote: ""
        yield: ""
        ingredients: ""
        totalTime: ""
        prepTime: ""
        cookTime: ""