defaults:

  - scope:
        path: ""
        type: posts

    values:
        layout: "recipe"

        image: ""
        tags: []

        source: "[site name or book name]"
        sourceURL: ""
        sourceAuthor: "by [Author], p[n]"

        yield: "Makes []"

        authorNote: ""
        personalNote: ""

        ingredients: []

        totalTime: ""

        times:
          - name: "Prep time"
            value: ""
          - name: "Hands-off time"
            value: ""
          - name: "Cook time"
            value: ""
          - name: "Chill time"
            value: ""
          - name: "Assembly time"
            value: ""
          - name: "Reheat time"
            value: ""

  - scope:
        path: ""
        type: posts

    values:
        layout: "default"

        image: ""
        tags: []

