defaults:

  - scope:
        path: ""
        type: posts
    values:
        layout: "recipe"

        image: ""
        tags: []

        source: "site name or book name"
        sourceURL: ""
        sourceAuthor: "by [Author], p[n]"

        yield: "Makes _"

        authorNote: ""
        personalNote: ""

        ingredients: []

        totalTime: ""
        prepTime: ""
        handsoffTime: ""
        cookTime: ""
        assemblyTime: ""
        reheatTime: ""

  - scope:
        path: ""
        type: posts
    values:
        layout: "default"
